# Generated by Django 3.0.7 on 2020-06-30 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='release_data',
            new_name='release_date',
        ),
    ]
