# Generated by Django 3.0.7 on 2020-07-01 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20200701_0744'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayScore',
            new_name='PlayerScore',
        ),
    ]
