# Generated by Django 3.0.7 on 2020-07-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20200701_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
